### ISSUE TITLE
paths can be unicode

### ISSUE THREAD

**Issue by michamos** [inspirehep/plotextractor#21]
Directories and files are user generated, so might contain characters outside of ascii. This should be taken into account. See https://sentry.cern.ch/inspire-sentry/inspire-labs/group/824581/ which is due to `tex_file = '/opt/inspire/var/data/workflows/files/6a/d2/e888-d822-40e3-a8cb-3982a2c8cc7c/data_files/carpeta sin título/three-methods.tex'`.

**Comment by david-caro** [comment]
happens also with the image names in `plotextractor/output_utils.py` in `get_image_location` at line 227 for ex with `image` = `u'轨道力学_p37.png'`.

**Comment by michamos** [comment]
Fixed in #29.
